#!/usr/bin/env ruby

require 'chbs'
require 'json'
require 'nokogiri'

def tv_and_movies
  corpus = {}
  
  datadir = File.expand_path('../wiktionary/tv-and-movies/', __FILE__)
  Dir.foreach(datadir) do |file|
    next if file == '.' || file == '..'
    doc = Nokogiri::HTML(File.open(File.join(datadir, file)))
    first = true
    doc.xpath("/html/body/div[@id='content']/div[@id='bodyContent']/div[@class='mw-content-ltr']/table/tr").each do |tr|
      # Skip the header line
      if first
        first = false
        if tr.at_xpath('td/b')
          next
        end
      end
      
      # <tr>
      # <td>1</td>
      # <td><a href="/wiki/you" title="you">you</a></td>
      # <td>1222421</td>
      # </tr>
      # <tr>
      td = tr.xpath('td').to_a
      # Ignore some cruft in a few files
      next if td[0].content.include?('-----')
      rank = td[0].content
      word = td[1].at_xpath('a').content
      count = td[2].content
      next if reject_word?(word)
      
      corpus[word.length] ||= []
      corpus[word.length] << word
    end
  end
  
  File.open(File.join(Chbs::CORPORA_DIRECTORY, 'tv-and-movies.json'), 'w') do |file|
    file.write corpus.to_json
  end
end

def gutenberg
  corpus = {}
  
  datadir = File.expand_path('../wiktionary/gutenberg/', __FILE__)
  Dir.foreach(datadir) do |file|
    next if file == '.' || file == '..'
    doc = Nokogiri::HTML(File.open(File.join(datadir, file)))
    doc.xpath("/html/body/div[@id='content']/div[@id='bodyContent']/div[@class='mw-content-ltr']/p/a").each do |a|
      word = a.content
      next if reject_word?(word)
      corpus[word.length] ||= []
      corpus[word.length] << word
    end
  end
  
  File.open(File.join(Chbs::CORPORA_DIRECTORY, 'gutenberg.json'), 'w') do |file|
    file.write corpus.to_json
  end
end

def reject_word?(word)
  # Skip contractions
  return true if word.include?("'")
  # Skip proper names and capitalized words
  return true if word =~ /^[A-Z]/
  # Skip non-ASCII words
  return true if word =~ /[^a-z]/
  # Skip compound words
  return true if word.include?('-')
  
  false
end

if !ARGV[0] || ARGV[0] == 'tv-and-movies'
  tv_and_movies
end
if !ARGV[0] || ARGV[0] == 'gutenberg'
  gutenberg
end
